version: '3.3'
services:
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    volumes: 
     - vol1:/mongo/data/db
  web:
    image: denistk/labelitjs:latest
    build: .
    command: "npm start"
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - "mongo"
volumes: 
   vol1:
      driver: local