version: '3'
services:
  web:
    image: denistk/labelitjs:latest
    build: .
    command: "npm start"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes: 
      - "~/mongo/data:/data/db"
